apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketpy-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.marketpy.local
    secretName: marketpy-tls
  rules:
  - host: api.marketpy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: marketpy-backend
            port:
              number: 80
