"""Paper trading engine for live simulation without real money.

This engine:
1. Receives live market updates
2. Runs strategies in "shadow mode" (generates signals, simulates fills)
3. Tracks simulated portfolio performance
4. Broadcasts signals and fills to WebSocket clients
"""

from __future__ import annotations

import asyncio
import logging
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from statistics import pstdev
from typing import Any
from uuid import uuid4

from backend.app.config_manager import ConfigManager
from backend.app.integrations.discord_notifier import DiscordNotifier, NotificationCategory
from backend.app.models.config import settings
from backend.app.models.market import Candle, MarketState, OrderBookSnapshot, Side
from backend.app.models.portfolio import Portfolio, Trade
from backend.app.realtime.memory_manager import MemoryManager
from backend.ml.prediction_tracker import get_prediction_tracker
from backend.paper_trading.live_feed import LiveFeedUpdate
from backend.sim.engine import Order
from backend.sim.fill_model import FillModelLevel, fill_order
from backend.sim.portfolio import PortfolioManager
from backend.strategies.adapter import AdapterContext, StrategyAdapter
from backend.strategies.freqtrade_interface import has_freqtrade_interface

try:
    import pandas as pd
except Exception:  # pragma: no cover - optional at runtime
    pd = None  # type: ignore[assignment]

logger = logging.getLogger(__name__)


@dataclass
class PaperTrade(Trade):
    """A paper trade with additional metadata."""

    simulated: bool = True
    signal_confidence: float = 0.0
    expected_edge: float = 0.0


@dataclass
class SignalEvent:
    """A signal generated by a strategy."""

    market_id: str
    timestamp: datetime
    signal_type: str  # BUY, SELL, HOLD
    confidence: float
    edge: float
    reason: str
    predicted_price: float | None = None
    current_price: float | None = None


@dataclass(slots=True)
class RiskLimits:
    max_position_per_market: float
    max_total_exposure: float
    max_daily_loss: float


class PaperTradingEngine:
    """Paper trading engine for live simulation.
    
    Usage:
        engine = PaperTradingEngine()
        engine.add_strategy(my_strategy)
        engine.add_ui_handler(broadcast_to_frontend)
        
        # Connect to live feed
        live_feed.add_handler(engine.on_market_update)
        await live_feed.start(token_ids)
    """

    def __init__(
        self,
        initial_cash: float = 10000.0,
        fill_model: str = "M2",
        fee_rate: float = 0.02,
        risk_limits: RiskLimits | None = None,
        discord_notifier: DiscordNotifier | None = None,
    ) -> None:
        self.initial_cash = initial_cash
        self.fill_model = FillModelLevel(fill_model)
        self.fee_rate = fee_rate
        self.risk_limits = risk_limits or RiskLimits(
            max_position_per_market=settings.max_position_per_market,
            max_total_exposure=settings.max_total_exposure,
            max_daily_loss=settings.max_daily_loss,
        )
        self.discord_notifier = discord_notifier

        self.pm = PortfolioManager(initial_cash=initial_cash)
        self.markets: dict[str, MarketState] = {}
        self.strategies: list = []
        self._ui_handlers: list[Callable[[str, dict], None]] = []
        self._dataframes: dict[str, Any] = {}

        self._running = False
        self._signal_count = 0
        self._trade_count = 0
        self._risk_violation_count = 0
        self._last_signal_time: dict[str, datetime] = {}
        self._last_hold_event_time: dict[str, datetime] = {}

        cfg = ConfigManager().get_system_config()
        self.min_signal_cooldown = cfg.min_signal_cooldown_seconds
        self.max_signal_cooldown = cfg.max_signal_cooldown_seconds
        self.volatility_window_seconds = cfg.volatility_window_seconds
        self.volatility_threshold_low = cfg.volatility_threshold_low
        self.volatility_threshold_high = cfg.volatility_threshold_high
        self._market_cooldowns: dict[str, float] = {}
        self._market_returns: dict[str, deque[tuple[datetime, float]]] = {}
        self.memory_manager = MemoryManager(cfg.memory)

        # Backward-compatible default static cooldown.
        self.signal_cooldown = int(self.max_signal_cooldown)
        self.hold_event_interval = 5
        self.prediction_tracker = get_prediction_tracker()
        self._daily_pnl_snapshot = 0.0
        self._daily_pnl_date = datetime.now(UTC).date()

    def add_strategy(self, strategy) -> None:
        """Add a trading strategy."""
        if not has_freqtrade_interface(strategy) and hasattr(strategy, "on_bar"):
            strategy = StrategyAdapter(
                strategy,
                AdapterContext(
                    markets_provider=lambda: self.markets,
                    portfolio_provider=lambda: self.pm.portfolio,
                ),
            )
        self.strategies.append(strategy)
        logger.info(f"Added strategy: {strategy.__class__.__name__}")

    def add_ui_handler(self, handler: Callable[[str, dict], None]) -> None:
        """Add a handler for UI updates (signals, trades, etc)."""
        self._ui_handlers.append(handler)

    async def _notify_ui(self, event_type: str, data: dict) -> None:
        """Notify all UI handlers of an event."""
        for handler in self._ui_handlers:
            try:
                if asyncio.iscoroutinefunction(handler):
                    await handler(event_type, data)
                else:
                    handler(event_type, data)
            except Exception as e:
                logger.error(f"UI handler error: {e}")

    def register_market(self, market_id: str, market_info: dict | None = None) -> None:
        """Register a market for paper trading."""
        if market_id not in self.markets:
            from backend.app.models.market import MarketInfo
            question = market_info.get("question", f"Market {market_id}") if market_info else f"Market {market_id}"
            info = MarketInfo(
                condition_id=market_id,
                question=question,
                token_id_yes=market_id,
            )

            self.markets[market_id] = MarketState(info=info)
            logger.info(f"Registered market: {market_id}")

    async def on_market_update(self, update: LiveFeedUpdate) -> None:
        """Handle incoming market update from live feed.
        
        This is the main entry point for live data.
        """
        if not self._running:
            return

        market_id = update.market_id

        # Auto-register unknown markets
        if market_id not in self.markets:
            self.register_market(market_id)

        # Update market state
        state = self.markets[market_id]
        effective_orderbook = update.orderbook
        if effective_orderbook is None and update.mid is not None and update.mid > 0:
            # Binance ticker stream provides top-of-book fields directly.
            # Build a synthetic snapshot so fills/mark-to-market can operate.
            bid = update.bid if update.bid is not None and update.bid > 0 else update.mid * 0.9999
            ask = update.ask if update.ask is not None and update.ask > 0 else update.mid * 1.0001
            if ask < bid:
                ask = bid
            mid = (bid + ask) / 2
            effective_orderbook = OrderBookSnapshot(
                token_id=market_id,
                timestamp=update.timestamp,
                best_bid=bid,
                best_ask=ask,
                mid=mid,
                spread=ask - bid,
            )

        if effective_orderbook is not None:
            state.orderbook = effective_orderbook
        if update.last_trade:
            state.last_trade_price = update.last_trade
        if state.orderbook and state.orderbook.mid is not None:
            mid = state.orderbook.mid
            bid = state.orderbook.best_bid or mid
            ask = state.orderbook.best_ask or mid
            spread = (
                state.orderbook.spread
                if state.orderbook.spread is not None
                else (ask - bid)
            )
            state.candles.append(
                Candle(
                    timestamp=update.timestamp,
                    open=mid,
                    high=mid,
                    low=mid,
                    close=mid,
                    mid=mid,
                    bid=bid,
                    ask=ask,
                    spread=spread,
                    volume=0.0,
                    trade_count=0,
                )
            )
            self.memory_manager.add_candle(market_id, state.candles[-1])
            state.candles = self.memory_manager.get_candles(market_id)
            self._append_dataframe_row(
                market_id=market_id,
                timestamp=update.timestamp,
                open_=mid,
                high=mid,
                low=mid,
                close=mid,
                volume=0.0,
                bid=bid,
                ask=ask,
                mid=mid,
                spread=spread,
            )
            self._update_market_volatility(market_id, update.timestamp, mid)
        state.updated_at = update.timestamp
        if update.mid and update.mid > 0:
            self.prediction_tracker.record_market_price(market_id, update.timestamp, update.mid)

        # Run strategies
        await self._evaluate_strategies(market_id, update)

        # Mark to market
        await self._mark_to_market(update.timestamp)

    def _append_dataframe_row(
        self,
        market_id: str,
        timestamp: datetime,
        open_: float,
        high: float,
        low: float,
        close: float,
        volume: float,
        bid: float,
        ask: float,
        mid: float,
        spread: float,
    ) -> None:
        if pd is None:
            return
        row = {
            "timestamp": timestamp,
            "open": open_,
            "high": high,
            "low": low,
            "close": close,
            "volume": volume,
            "bid": bid,
            "ask": ask,
            "mid": mid,
            "spread": spread,
        }
        df = self._dataframes.get(market_id)
        if df is None:
            self._dataframes[market_id] = pd.DataFrame([row])
            return
        updated = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
        self._dataframes[market_id] = updated.tail(100).reset_index(drop=True)

    async def _evaluate_strategies(self, market_id: str, update: LiveFeedUpdate) -> None:
        """Run all strategies on the market update."""
        for strategy in self.strategies:
            try:
                # Check cooldown
                last_time = self._last_signal_time.get(market_id)
                cooldown = self.get_market_cooldown(market_id)
                if last_time and (update.timestamp - last_time).total_seconds() < cooldown:
                    continue

                orders: list[Order] = []
                if has_freqtrade_interface(strategy) and pd is not None:
                    df = self._dataframes.get(market_id)
                    if df is not None and not df.empty:
                        enriched = strategy.populate_indicators(df.copy())
                        entry_df = strategy.populate_entry_trend(enriched.copy())
                        signal_df = strategy.populate_exit_trend(entry_df.copy())
                        latest = signal_df.iloc[-1]
                        order_size = float(getattr(strategy, "order_size", 1.0))
                        if bool(latest.get("enter_long", False)):
                            orders.append(
                                Order(
                                    market_id=market_id,
                                    side=Side.BUY,
                                    size=order_size,
                                    strategy=getattr(strategy, "strategy_name", strategy.__class__.__name__),
                                )
                            )
                        if bool(latest.get("exit_long", False)):
                            current = self.pm.get_position_size(market_id)
                            if current > 0:
                                orders.append(
                                    Order(
                                        market_id=market_id,
                                        side=Side.SELL,
                                        size=min(order_size, current),
                                        strategy=getattr(
                                            strategy, "strategy_name", strategy.__class__.__name__
                                        ),
                                    )
                                )
                elif hasattr(strategy, "on_bar"):
                    # Backward-compatible strategy interface.
                    raw_orders = strategy.on_bar(markets=self.markets, portfolio=self.pm.portfolio)
                    if raw_orders:
                        orders.extend(raw_orders)
                    signal_map = getattr(strategy, "last_signals", None)
                    if isinstance(signal_map, dict):
                        latest_signal = signal_map.get(market_id)
                        if latest_signal is not None:
                            self.prediction_tracker.record_signal(latest_signal)
                            try:
                                from backend.app.routers import signals as signals_router

                                signals_router._signals[market_id] = latest_signal
                            except (AttributeError, ImportError, KeyError):
                                pass

                if not orders:
                    last_hold = self._last_hold_event_time.get(market_id)
                    if (
                        last_hold is None
                        or (update.timestamp - last_hold).total_seconds() >= self.hold_event_interval
                    ):
                        await self._notify_ui(
                            "signal",
                            {
                                "market_id": market_id,
                                "decision": "HOLD",
                                "confidence": 0.0,
                                "edge": 0.0,
                                "edge_pct": 0.0,
                                "current_mid": update.mid,
                                "predicted_price": None,
                                "reason": "No actionable signal yet",
                                "strategy": getattr(
                                    strategy,
                                    "strategy_name",
                                    getattr(strategy, "name", strategy.__class__.__name__),
                                ),
                            },
                        )
                        self._last_hold_event_time[market_id] = update.timestamp
                    continue

                for order in orders:
                    if order.market_id != market_id:
                        continue
                    await self._process_order(order, update)
                    self._last_signal_time[market_id] = update.timestamp

            except (AttributeError, KeyError, RuntimeError, TypeError, ValueError) as e:
                logger.error(f"Strategy error for {market_id}: {e}")

    async def _process_order(
        self,
        order: Order,
        update: LiveFeedUpdate,
    ) -> None:
        """Process a strategy order in paper mode."""
        self._signal_count += 1

        side = order.side
        market_id = order.market_id
        size = order.size

        # Check position limits
        current_size = self.pm.get_position_size(market_id)
        if side == Side.SELL and current_size <= 0:
            logger.warning(f"Cannot SELL {market_id}: no position")
            return
        if side == Side.BUY and current_size >= self.risk_limits.max_position_per_market:
            await self._handle_risk_violation(
                "max_position_per_market",
                market_id,
                current_size,
                self.risk_limits.max_position_per_market,
            )
            return

        # Execute paper trade
        market_state = self.markets.get(market_id)
        orderbook = update.orderbook or (market_state.orderbook if market_state else None)
        if orderbook:
            ref_mid = orderbook.mid if orderbook.mid is not None else 0.0
            projected_exposure = self.pm.portfolio.positions_value + max(0.0, size * ref_mid)
            if side == Side.BUY and projected_exposure > self.risk_limits.max_total_exposure:
                await self._handle_risk_violation(
                    "max_total_exposure",
                    market_id,
                    projected_exposure,
                    self.risk_limits.max_total_exposure,
                )
                return
            daily_pnl = self._current_daily_pnl()
            if daily_pnl <= -self.risk_limits.max_daily_loss:
                await self._handle_risk_violation(
                    "max_daily_loss",
                    market_id,
                    -daily_pnl,
                    self.risk_limits.max_daily_loss,
                )
                return

            fill = fill_order(
                side=side,
                size=size,
                orderbook=orderbook,
                model=self.fill_model,
                fee_rate=self.fee_rate,
                fee_exponent=settings.default_fee_exponent,
                limit_price=order.limit_price,
            )

            if fill.filled:
                trade = self.pm.record_fill(
                    market_id=market_id,
                    side=side,
                    fill=fill,
                    strategy=order.strategy,
                    edge=order.edge,
                    timestamp=update.timestamp,
                )
                self._trade_count += 1

                # Notify UI of trade
                await self._notify_ui("trade", {
                    "market_id": market_id,
                    "side": side.value,
                    "size": size,
                    "price": trade.price,
                    "fee": fill.fee,
                    "pnl": trade.pnl,
                    "strategy": trade.strategy,
                    "edge": trade.edge,
                })
                await self._maybe_notify_trade(trade=trade, size=size)

                logger.info(
                    f"Paper trade: {side.value} {size} {market_id} @ {trade.price:.4f}"
                )

        # Always notify UI of generated order
        await self._notify_ui("signal", {
            "market_id": market_id,
            "decision": side.value,
            "confidence": 0.0,
            "edge": order.edge or 0.0,
            "edge_pct": 0.0,
            "current_mid": update.mid,
            "predicted_price": None,
            "reason": "Order generated by strategy.on_bar",
            "strategy": order.strategy,
        })

    def _current_daily_pnl(self) -> float:
        today = datetime.now(UTC).date()
        if today != self._daily_pnl_date:
            self._daily_pnl_date = today
            self._daily_pnl_snapshot = self.pm.portfolio.total_pnl
        return self.pm.portfolio.total_pnl - self._daily_pnl_snapshot

    async def _maybe_notify_trade(self, trade, size: float) -> None:
        if self.discord_notifier is None:
            return
        notional = abs(size * trade.price)
        if notional < 10_000:
            return
        await self.discord_notifier.send(
            category=NotificationCategory.TRADE,
            component="paper_trading_engine",
            message=f"Large paper trade executed: {trade.market_id} {trade.action.value}",
            metrics={
                "notional": round(notional, 2),
                "price": round(trade.price, 6),
                "size": round(size, 6),
            },
        )

    async def _handle_risk_violation(
        self,
        limit_type: str,
        market_id: str,
        current_value: float,
        limit_value: float,
    ) -> None:
        self._risk_violation_count += 1
        correlation_id = str(uuid4())
        payload = {
            "timestamp": datetime.now(UTC).isoformat(),
            "limit_type": limit_type,
            "market_id": market_id,
            "current_value": current_value,
            "limit_value": limit_value,
            "correlation_id": correlation_id,
        }
        logger.warning("risk_limit_violation %s", payload)
        await self._notify_ui("risk_alert", payload)
        if self.discord_notifier is not None:
            await self.discord_notifier.send(
                category=NotificationCategory.RISK,
                component="paper_trading_engine",
                message=f"Risk limit breach: {limit_type}",
                metrics={
                    "market_id": market_id,
                    "current_value": round(current_value, 6),
                    "limit_value": round(limit_value, 6),
                    "correlation_id": correlation_id,
                },
            )

    async def _maybe_notify_daily_pnl(self) -> None:
        if self.discord_notifier is None:
            return
        pnl_pct = (self.pm.portfolio.total_pnl / self.initial_cash) if self.initial_cash else 0.0
        if abs(pnl_pct) < 0.05:
            return
        await self.discord_notifier.send(
            category=NotificationCategory.INFO,
            component="paper_trading_engine",
            message="Daily PnL threshold reached",
            metrics={
                "total_pnl": round(self.pm.portfolio.total_pnl, 4),
                "pnl_pct": round(pnl_pct * 100, 3),
                "equity": round(self.pm.portfolio.total_equity, 4),
            },
        )

    async def _mark_to_market(self, timestamp: datetime) -> None:
        """Update portfolio with current market prices."""
        prices = {}
        for market_id, state in self.markets.items():
            if state.orderbook and state.orderbook.mid is not None:
                prices[market_id] = state.orderbook.mid

        if prices:
            self.pm.mark_to_market(prices, timestamp=timestamp)

        # Notify UI of portfolio update
        await self._notify_ui("portfolio", {
            "cash": self.pm.portfolio.cash,
            "total_equity": self.pm.portfolio.total_equity,
            "total_pnl": self.pm.portfolio.total_pnl,
            "total_pnl_pct": self.pm.portfolio.total_pnl_pct,
            "unrealized_pnl": sum(
                pos.unrealized_pnl for pos in self.pm.portfolio.positions.values()
            ),
            "realized_pnl": self.pm.portfolio.realized_pnl,
            "positions_count": len(self.pm.portfolio.positions),
            "trades_count": len(self.pm.portfolio.trades),
            "max_drawdown": self.pm.portfolio.max_drawdown,
        })
        await self._maybe_notify_daily_pnl()

    def start(self) -> None:
        """Start the paper trading engine."""
        self._running = True
        logger.info("Paper trading engine started")

    def stop(self) -> None:
        """Stop the paper trading engine."""
        self._running = False
        logger.info("Paper trading engine stopped")

    def reset(self) -> None:
        """Reset the paper trading engine to initial state."""
        self.pm = PortfolioManager(initial_cash=self.initial_cash)
        self.markets.clear()
        self._dataframes.clear()
        self._signal_count = 0
        self._trade_count = 0
        self._risk_violation_count = 0
        self._last_signal_time.clear()
        self._last_hold_event_time.clear()
        self._market_cooldowns.clear()
        self._market_returns.clear()
        self._daily_pnl_snapshot = 0.0
        self._daily_pnl_date = datetime.now(UTC).date()
        logger.info("Paper trading engine reset")

    @property
    def is_running(self) -> bool:
        return self._running

    @property
    def portfolio(self) -> Portfolio:
        return self.pm.portfolio

    @property
    def stats(self) -> dict[str, Any]:
        return {
            "signal_count": self._signal_count,
            "trade_count": self._trade_count,
            "risk_violation_count": self._risk_violation_count,
            "market_count": len(self.markets),
            "total_equity": self.pm.portfolio.total_equity,
            "total_pnl": self.pm.portfolio.total_pnl,
            "is_running": self._running,
        }

    def get_risk_status(self) -> dict[str, Any]:
        position_sizes = {market_id: pos.size for market_id, pos in self.pm.portfolio.positions.items()}
        return {
            "limits": {
                "max_position_per_market": self.risk_limits.max_position_per_market,
                "max_total_exposure": self.risk_limits.max_total_exposure,
                "max_daily_loss": self.risk_limits.max_daily_loss,
            },
            "metrics": {
                "current_exposure": self.pm.portfolio.positions_value,
                "daily_pnl": self._current_daily_pnl(),
                "position_sizes": position_sizes,
            },
            "status": {
                "position_limit_ok": all(
                    size <= self.risk_limits.max_position_per_market for size in position_sizes.values()
                ),
                "exposure_limit_ok": self.pm.portfolio.positions_value <= self.risk_limits.max_total_exposure,
                "daily_loss_limit_ok": self._current_daily_pnl() > -self.risk_limits.max_daily_loss,
            },
            "risk_violation_count": self._risk_violation_count,
        }

    def get_market_cooldown(self, market_id: str) -> float:
        """Return current adaptive cooldown for a market."""
        return self._market_cooldowns.get(market_id, float(self.signal_cooldown))

    def get_all_cooldowns(self) -> dict[str, float]:
        return dict(self._market_cooldowns)

    def _update_market_volatility(self, market_id: str, ts: datetime, price: float) -> None:
        if price <= 0:
            return
        series = self._market_returns.setdefault(market_id, deque())
        series.append((ts, price))
        cutoff = ts.timestamp() - self.volatility_window_seconds
        while series and series[0][0].timestamp() < cutoff:
            series.popleft()

        if len(series) < 2:
            self._market_cooldowns[market_id] = float(self.max_signal_cooldown)
            return

        returns: list[float] = []
        prev = series[0][1]
        for _, current in list(series)[1:]:
            if prev > 0:
                returns.append((current - prev) / prev)
            prev = current
        volatility = pstdev(returns) if returns else 0.0
        self._market_cooldowns[market_id] = self._map_volatility_to_cooldown(volatility)

    def _map_volatility_to_cooldown(self, volatility: float) -> float:
        if volatility <= self.volatility_threshold_low:
            return float(self.max_signal_cooldown)
        if volatility >= self.volatility_threshold_high:
            return float(self.min_signal_cooldown)
        span = self.volatility_threshold_high - self.volatility_threshold_low
        pos = (volatility - self.volatility_threshold_low) / span
        cooldown = self.max_signal_cooldown - pos * (
            self.max_signal_cooldown - self.min_signal_cooldown
        )
        return float(max(self.min_signal_cooldown, min(self.max_signal_cooldown, cooldown)))
